// prisma/seed.js
import { PrismaClient } from '../generated/prisma/index.js'; // Matches the custom output path
import dotenv from 'dotenv';

// Load environment variables from .env file
dotenv.config();

const prisma = new PrismaClient();

async function main() {
  const songData = [
    // Original 6 songs
    {
      id: '1',
      title: 'Blinding Lights',
      artist: 'The Weeknd',
      duration: '3:20',
      cover: '/images/blinding-lights.jpg',
      filePath: '/songs/blinding-lights.mp3',
      genre: 'Pop',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '2',
      title: 'Levitating',
      artist: 'Dua Lipa',
      duration: '3:23',
      cover: '/images/levitating.jpg',
      filePath: '/songs/levitating.mp3',
      genre: 'Pop',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '3',
      title: 'Dreams',
      artist: 'Fleetwood Mac',
      duration: '4:17',
      cover: '/images/dreams.jpg',
      filePath: '/songs/dreams.mp3',
      genre: 'Rock',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '4',
      title: 'The Night We Met',
      artist: 'Lord Huron',
      duration: '3:28',
      cover: '/images/night-we-met.jpg',
      filePath: '/songs/night-we-met.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '5',
      title: 'Sicko Mode',
      artist: 'Travis Scott ft. Swae Lee & Drake',
      duration: '5:12',
      cover: '/images/sicko-mode.jpg',
      filePath: '/songs/sicko-mode.mp3',
      genre: 'Hip-Hop',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '6',
      title: 'Sweet Jane',
      artist: 'The Velvet Underground',
      duration: '4:06',
      cover: '/images/sweet-jane.jpg',
      filePath: '/songs/sweet-jane.mp3',
      genre: 'Rock',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    // Your 19 songs (corrected)
    {
      id: '7',
      title: 'Afusic',
      artist: 'Unknown Artist',
      duration: '3:10',
      cover: '/images/afusic.jpg',
      filePath: '/songs/afusic.mp3',
      genre: 'Unknown',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '8',
      title: 'Baraat',
      artist: 'Ritviz',
      duration: '3:29',
      cover: '/images/baraat.jpg',
      filePath: '/songs/baraat.mp3',
      genre: 'Electronic',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '9',
      title: 'Bawe',
      artist: 'Badshah',
      duration: '3:15',
      cover: '/images/bawe.jpg',
      filePath: '/songs/bawe.mp3',
      genre: 'Hip-Hop',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '10',
      title: 'Cold Mess',
      artist: 'Prateek Kuhad',
      duration: '4:01',
      cover: '/images/cold-mess.jpg',
      filePath: '/songs/cold-mess.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '11',
      title: 'Fasle',
      artist: 'Aditya Rikhari',
      duration: '3:45',
      cover: '/images/fasle.jpeg',
      filePath: '/songs/fasle.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '12',
      title: 'Iradey',
      artist: 'Abdul Hannan',
      duration: '3:50',
      cover: '/images/iradey.jpg',
      filePath: '/songs/iradey.mp3',
      genre: 'Pop',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '13',
      title: 'Kya Tu Theek Hai',
      artist: 'Arpit Bala',
      duration: '3:40',
      cover: '/images/kya-tu-theek-hai.png',
      filePath: '/songs/kya-tu-theek-hai.mp3',
      genre: 'Hip-Hop',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '14',
      title: 'Lumineer',
      artist: 'Unknown Artist',
      duration: '3:30',
      cover: '/images/lumineer.jpg',
      filePath: '/songs/lumineer.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '15',
      title: 'Maharani',
      artist: 'Karan Aujla',
      duration: '3:20',
      cover: '/images/maharani.jpg',
      filePath: '/songs/maharani.mp3',
      genre: 'Punjabi Pop',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '16',
      title: 'Mann',
      artist: 'The Yellow Diary',
      duration: '4:05',
      cover: '/images/mann.jpg',
      filePath: '/songs/Mann.mp3',
      genre: 'Indie Rock',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '17',
      title: 'Mujhe Tum Nazar Se',
      artist: 'Mehdi Hassan',
      duration: '5:20',
      cover: '/images/mujhe-tum-nazar-se.jpg',
      filePath: '/songs/mujhe-tum-nazar-se.mp3',
      genre: 'Ghazal',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '18',
      title: 'Neighbourhood Sweater',
      artist: 'Unknown Artist',
      duration: '3:25',
      cover: '/images/neighbourhood.jpg',
      filePath: '/songs/neighbourhood-sweater.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '19',
      title: 'Pal Pal',
      artist: 'Afusic',
      duration: '4:12',
      cover: '/images/afusic.jpeg',
      filePath: '/songs/pal-pal.mp3',
      genre: 'Bollywood',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '20',
      title: 'Paro',
      artist: 'Aditya Rikhari',
      duration: '3:30',
      cover: '/images/paro.jpg',
      filePath: '/songs/paro.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '21',
      title: 'Rab Da Banda',
      artist: 'Ahen ft Gumroh',
      duration: '3:55',
      cover: '/images/rab-da-banda.jpg',
      filePath: '/songs/rab-da-banda.mp3',
      genre: 'Devotional Bhajan',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '22',
      title: 'Sunday',
      artist: 'Aditya A',
      duration: '3:10',
      cover: '/images/sunday.jpeg',
      filePath: '/songs/sunday.mp3',
      genre: 'Pop',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '23',
      title: 'Teenage Dreams',
      artist: 'Unknown Artist',
      duration: '3:45',
      cover: '/images/teenage-dreams.jpg',
      filePath: '/songs/teenage-dreams.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '24',
      title: 'Tu Hoti Toh',
      artist: 'Bharat Chauhan',
      duration: '4:00',
      cover: '/images/tu-hoti-toh.jpg',
      filePath: '/songs/tu-hoti-toh.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
    {
      id: '25',
      title: 'When U High',
      artist: 'Arctic Monkeys',
      duration: '3:30',
      cover: '/images/Ar.jpeg',
      filePath: '/songs/when-u-high.mp3',
      genre: 'Indie',
      likes: 0,
      plays: 0,
      liked: false,
      artistId: null,
    },
  ];

  for (const song of songData) {
    await prisma.song.upsert({
      where: { id: song.id },
      update: song,
      create: song,
    });
  }

  console.log('Seeded 25 songs successfully');
}

main()
  .catch((e) => {
    console.error('Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });